spark-operator:
  crds:
    install: false
  operator:
    imageName: gcr.io/spark-operator/spark-operator
    imageTag: v1beta2-1.3.8-3.1.1
    namespace: spark-operator
  controller:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
  sparkJobNamespace: spark-jobs
  webhook:
    enable: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  rbac:
    create: true
