apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/platform.yaml
  - applications/traefik.yaml
  - applications/cert-manager.yaml
  - applications/spark-operator.yaml
  - applications/minio.yaml
  - applications/airflow.yaml
